export interface IDoctor {
    id: number,
    userId: number,
    avatarUrl: string,
    email: string,
    password: string,
    role: string,
    phone: string,
    status: string,
    medCentreId: string,
    firstName: string,
    lastName: string,
    fatherName: string,
    age: string,
    yearStarted: string,
    medService: string,
    description: string,
}

export interface INewDoctor {
    email: string,
    password: string,
    phone: string,
    status: string,
    medCentreId: string,
    firstName: string,
    lastName: string,
    fatherName: string,
    age: string,
    yearStarted: string,
    medService: string,
    description: string,
}

export const initDoctor: IDoctor = {
    id: 0,
    userId: 0,
    avatarUrl: "",
    email: "",
    password: "",
    role: "",
    phone: "",
    status: "",
    medCentreId: "",
    firstName: "",
    lastName: "",
    fatherName: "",
    age: "",
    yearStarted: "",
    medService: "",
    description: "",
}